name: Frontend CD

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build] # Ensure 'build' job from frontend-ci.yml is successful

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist # Or the path you used in upload-artifact

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            rm -rf /var/www/your-frontend-app/* # Remove old files, adjust path
            cp -r dist/* /var/www/your-frontend-app # Copy new build, adjust path
            # Optionally, restart web server if needed (e.g., Nginx)
            # sudo systemctl restart nginx