services:
  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3 